config/routes.rb
Todos::Application.routes.draw do
  root to: "todos#index"

  resources "todos", only: [:index, :new, :create] do
  	resource :completion, only: [:create, :destroy]
  end

  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create", as: "signin_post"
end

app/models/todo.rb
class Todo < ActiveRecord::Base

	def complete!
		touch(:completed_at)
	end

	def incomplete!
		update!(completed_at: nil)
	end

	def completed?
		completed_at?		# rails generated method
	end

end

app/models/user.rb
class User

	def initialize email
		@email = email
	end

	def todos
		Todo.where(email: @email)
	end

	def signed_in?
		@email.present?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def must_signed_in
  	redirect_to signin_path unless signed_in?
  end

  def signed_in?
  	current_user.signed_in?
  end

  def sign_in_as email
  	session[:current_email] = email
  end

  def current_user
    @current_user ||= User.new(session[:current_email])
  end

end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
	
	def create
		todo.complete!
		redirect_to todos_path
	end

	def destroy
		todo.incomplete!
		redirect_to todos_path
	end

	private

		def todo
			# for security' sake
			current_user.todos.find(params[:todo_id])
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new			
	end

	def create
		sign_in_as params[:session][:email]
		redirect_to root_path
	end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	before_action :must_signed_in

	def index
		@todos = current_user.todos
	end

	def new
		@todo = Todo.new
	end

	def create
		current_user.todos.create(todo_params)
		redirect_to todos_path
	end

	private

		def todo_params
			params.require(:todo).permit(:title)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h1>Todos</h1>

	<%= yield %>

</body>
</html>

app/views/todos/_todo.html.erb
<li class="<%= "completed" if todo.completed? %>">
	<%= todo.title %>

	<% if todo.completed? %>
		<%= button_to "Mark as Incompleted", todo_completion_path(todo), method: :delete %>
	<% else %>
		<%= button_to "Mark as Completed", todo_completion_path(todo) %>
	<% end %>
</li>

app/views/todos/index.html.erb
<%= link_to "New Todo", new_todo_path %>

<ul class="todos">
	<%= render partial: "todo", collection: @todos %>
</ul>

app/views/todos/new.html.erb
<%= form_for @todo do |f| %>
	<%= f.label :title, "Title" %>
	<%= f.text_field :title %>

	<%= f.submit "Submit" %>
<% end %>